//
//  RestaurantFacts.swift
//  Ketchup
//
//  Created by Jack Robinson on 10/22/24.
//

import Foundation
let restaurantFacts = [
    "The word 'restaurant' comes from the French word 'restaurer,' which means 'to restore.'",
    "The oldest restaurant still in operation is Sobrino de Botín in Madrid, Spain, opened in 1725.",
    "McDonald's sells more than 75 hamburgers every second.",
    "The first drive-thru restaurant was created in 1948 by In-N-Out Burger.",
    "Pizza Hut delivered pizza to the International Space Station in 2001.",
    "The world’s largest restaurant is the Bawabet Dimashq (Damascus Gate) Restaurant in Syria, seating 6,014 people.",
    "In Japan, you can eat at robot-operated restaurants.",
    "Ketchup was once sold as medicine in the 1830s.",
    "The term 'fast food' was first recognized in the Merriam-Webster dictionary in 1951.",
    "There is a restaurant in Australia where you can eat while suspended 50 meters in the air.",
    "The Eiffel Tower has a Michelin-starred restaurant, Le Jules Verne, located 410 feet above ground.",
    "One of the smallest restaurants in the world is 'Solo per Due' in Italy, serving only two people at a time.",
    "The first pizzeria in the U.S. opened in 1905 in New York City.",
    "The 'happy meal' concept originated in Guatemala in the 1970s.",
    "Sushi chefs in Japan must train for over a decade before being considered a master.",
    "The most expensive pizza in the world, created by Renato Viola, costs around $12,000.",
    "The first restaurant to have a rotating dining room is the 'Top of the World' restaurant in Las Vegas.",
    "The restaurant industry employs over 15 million people in the U.S.",
    "The Cheesecake Factory’s menu has over 250 items!",
    "In Singapore, there’s a restaurant where diners eat in complete darkness.",
    "There’s a restaurant in China where all waiters are robots.",
    "Taco Bell was the first fast-food chain to open in outer space — on the Mir Space Station.",
    "The oldest American restaurant still in operation is the Union Oyster House in Boston, founded in 1826.",
    "The first Starbucks opened in Seattle, Washington, in 1971.",
    "The world’s longest restaurant table stretched over 2.4 km (1.49 miles).",
    "Some Michelin-starred restaurants serve tasting menus of over 20 courses.",
    "In Dubai, there’s an underwater restaurant, Ossiano, inside a giant aquarium.",
    "The French Laundry in California is one of the world’s most famous Michelin-starred restaurants.",
    "China has the highest number of restaurants globally, with over 8 million.",
    "The tradition of tipping started in England during the 17th century.",
    "In Japan, slurping your noodles is a sign of appreciation for the meal.",
    "The world’s most expensive restaurant is Sublimotion in Ibiza, with prices reaching up to $2,000 per person.",
    "Drive-thru lanes account for about 70% of fast food restaurant sales in the U.S.",
    "Chick-fil-A is the largest purchaser of peanut oil in the United States.",
    "Waffle House claims to have served over 2.5 billion waffles since its opening.",
    "The highest restaurant in the world is 'Chacaltaya' in Bolivia, located at 17,785 feet above sea level.",
    "The first fine dining restaurant in America was Delmonico’s in New York, opened in 1837.",
    "The 'all-you-can-eat' buffet concept originated in the 1940s in Las Vegas.",
    "In Italy, it is considered rude to ask for parmesan on pizza.",
    "The busiest restaurant day in the U.S. is Mother’s Day.",
    "Noma in Copenhagen, Denmark, was voted the world’s best restaurant several times.",
    "The McDonald's 'Golden Arches' are recognized by more people worldwide than the Christian cross.",
    "Some restaurants in the U.S. serve food out of food trucks, a growing trend in the culinary scene.",
    "TGI Fridays popularized the concept of casual dining in the 1960s.",
    "The world’s most expensive hamburger was sold for $5,000 at Juicys Outlaw Grill in Oregon.",
    "‘Restaurant Week’ started in New York City in 1992.",
    "The first food truck dates back to the 1860s when a Texas cattleman built a mobile kitchen.",
    "In Thailand, there's a restaurant where food is served by waiters dressed as pandas.",
    "French fries are the most popular side item in American restaurants.",
    "The first all-vegetarian restaurant opened in 1849 in London.",
    "Some high-end restaurants have secret menus that only frequent guests know about.",
    "The largest fast food chain in the world by locations is Subway.",
    "The first pizza delivery took place in 1889 in Naples, Italy, to Queen Margherita.",
    "Michelin Stars, awarded to restaurants, originated from the Michelin tire company to promote road trips.",
    "Restaurants use music, lighting, and seating arrangements to influence how fast you eat.",
    "In some sushi restaurants, the chef will refuse to serve soy sauce with certain dishes.",
    "The first fast food chain in America was White Castle, founded in 1921.",
    "Diners in Denmark pay nearly 25% VAT (sales tax) on their restaurant bills.",
    "The world's longest pizza measured 1.9 kilometers long.",
    "Some restaurants in New York have a 'no tipping' policy, with the cost of service included in the bill.",
    "Many high-end restaurants offer wine pairings customized to the tasting menu.",
    "‘Molecular gastronomy’ restaurants, like elBulli, use science to create unusual dishes.",
    "In Korea, restaurants use grills at the table for cooking your own food, called 'Korean BBQ.'",
    "Burger King is known as 'Hungry Jack's' in Australia.",
    "In France, it’s common to spend two hours or more on a multi-course meal.",
    "There are restaurants in Japan where all the food is prepared by ninjas.",
    "In Canada, ‘poutine,’ French fries topped with gravy and cheese curds, is a popular dish.",
    "Some restaurants offer 'pay-what-you-want' pricing to reduce food waste.",
    "Many Michelin-starred chefs have their own lines of cookware.",
    "There’s a restaurant in New York City that only serves peanut butter-based dishes.",
    "Alcatraz, the infamous prison, once had a highly regarded cafeteria.",
    "Some restaurants in London have a no-reservation policy, meaning long waits.",
    "The most popular ethnic cuisine in the U.S. is Italian.",
    "The concept of ‘farm-to-table’ restaurants focuses on using local and organic ingredients.",
    "A common practice in high-end sushi restaurants is serving fish caught the same day.",
    "Some restaurants in Sweden offer discounts to patrons who arrive by bicycle.",
    "In Germany, you’ll find many self-service restaurants called 'imbiss.'",
    "The oldest continuously operating soda fountain in the U.S. is in St. Louis, Missouri.",
    "There are cat-themed restaurants in Japan, where cats roam freely.",
    "In Portugal, it’s common to serve salted cod (bacalhau) in hundreds of ways.",
    "Modern-day ramen shops are inspired by Chinese noodle houses.",
    "In Peru, you’ll find restaurants that serve guinea pig as a delicacy.",
    "Some restaurants in Iceland serve fermented shark, a traditional dish.",
    "‘Diners, Drive-Ins, and Dives’ has highlighted hundreds of unique restaurants in the U.S.",
    "The Michelin Guide was originally a free publication to encourage travel.",
    "In Spain, tapas are small dishes served with drinks, originally to cover the glass (tapas means 'lid').",
    "In Vietnam, street vendors serve pho (noodle soup) from tiny stalls.",
    "In Italy, the ‘slow food’ movement began to promote traditional cooking and sustainable eating.",
    "Many luxury restaurants feature chef’s tables, offering a view of the kitchen.",
    "Some restaurants are entirely plant-based, catering to vegans and vegetarians.",
    "The world’s largest bowl of pasta weighed more than 17,000 pounds.",
    "The 'Supper Club' movement in the U.S. began in the 1930s and 1940s as elegant dining experiences.",
    "Spain’s elBulli, once the top-rated restaurant in the world, closed to become a culinary think tank.",
    "Michelin-Star inspectors dine anonymously to ensure unbiased reviews.",
    "Some restaurants charge a 'corkage fee' when guests bring their own wine.",
    "The busiest McDonald's is in Moscow, Russia, serving over 40,000 people daily.",
    "Drive-thru funeral parlors in the U.S. have partnered with fast food restaurants to offer food service.",
    "Some exclusive restaurants have waiting lists months or even years long.",
    "The Guinness World Record for the most expensive taco, created by a restaurant in Mexico, costs $25,000.",
    "The smallest restaurant in the world is only 1.8 square meters and seats just two people.",
    "In Thailand, there is a restaurant where monkeys serve the food.",
    "The world’s first pizza vending machine was introduced in Italy in 2009.",
    "The first food delivery service started in 1889 in Naples, Italy, delivering pizza.",
    "Ruth’s Chris Steak House got its name when the original restaurant burned down, and the founder had to buy a new one.",
    "Panda Express was created by Chinese immigrants and became one of the most popular Asian fast food chains in America.",
    "Many Michelin-starred restaurants have a waitlist over a year long.",
    "Restaurants in Singapore often include 'service charge' as a replacement for tipping.",
    "One of the world's rarest foods, white truffles, can cost more than $3,000 per pound.",
    "McDonald’s once tested spaghetti on its menu.",
    "The phrase 'fine dining' refers to restaurants that offer high-quality service and more elaborate menus."
]
