//
//  Cuisine Options.swift
//  Foodi
//
//  Created by Jack Robinson on 4/2/24.
//

import Foundation
let cuisineCategories = [
    "American (New)",
    "American (Traditional)",
    "Asian Fusion",
    "Bakeries",
    "Barbeque",
    "Bars",
    "Breakfast & Brunch",
    "Burgers",
    "Cafes",
    "Chinese",
    "Cocktail Bars",
    "Coffee & Tea",
    "Delis",
    "Desserts",
    "Fast Food",
    "French",
    "Greek",
    "Indian",
    "Italian",
    "Japanese",
    "Juice Bars & Smoothies",
    "Korean",
    "Latin American",
    "Mediterranean",
    "Mexican",
    "Middle Eastern",
    "Noodles",
    "Pizza",
    "Poke",
    "Ramen",
    "Sandwiches",
    "Seafood",
    "Soul Food",
    "Southern",
    "Spanish",
    "Sports Bars",
    "Steakhouses",
    "Sushi Bars",
    "Tapas Bars",
    "Thai",
    "Vegan",
    "Vegetarian",
    "Vietnamese",
    "Wine Bars",
    "Wraps",
    "Cuban",
    "Ethiopian",
    "German",
    "Halal",
    "Malaysian",
    "Brazilian",
    "Cajun/Creole",
    "Caribbean",
    "Dim Sum",
    "Filipino",
    "Hawaiian",
    "Irish",
    "Lebanese",
    "Moroccan",
    "Peruvian",
    "Russian",
    "Salvadoran",
    "Scandinavian",
    "Taiwanese",
    "Turkish",
    "Healthy",
    "Buffet"
]
